### ISSUE TITLE
some caching issues...sometimes

### ISSUE THREAD

**Issue by cboisvenue** [cboisvenue/spadesCBM#33]
After restart of R studio, I et an error. Here is the error (image). But if I clearCache(spadesCBMsim) and rerun the spades call (```spadesCBMout <- spades(spadesCBMSim, debug = TRUE)```), it runs...
![cachingProblem](https://user-images.githubusercontent.com/11393605/94486181-dfb60380-0193-11eb-82cd-7d33aab525c2.PNG)

**Comment by achubaty** [comment]
This now resolved on `rmGlobalEnv` branch. Merging to `development`.
